# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='pay_id',
        ),
    ]
