# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=20)),
                ('Table', models.IntegerField(default=0)),
                ('Completed', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table', models.IntegerField(default=0)),
                ('Code', models.CharField(max_length=20)),
            ],
        ),
    ]
