# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 27, 1, 19, 56, 815280, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='alert',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
        ),
    ]
