# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Completed',
        ),
        migrations.AddField(
            model_name='order',
            name='Timestamp',
            field=models.CharField(choices=[(b'CRE', b'Order created'), (b'STK', b'Order sent to kitchen'), (b'STA', b'Order started'), (b'RDY', b'Order ready to be served'), (b'SER', b'Order served')], default=b'CRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
