# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20161127_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(verbose_name='time started'),
        ),
    ]
