# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orderedmenuitems_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmenuitems',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
