# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20161201_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
