# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20161125_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedmenuitems',
            old_name='Table_id',
            new_name='table_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 26, 20, 55, 43, 216000, tzinfo=utc)),
        ),
    ]
