# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuItems',
        ),
    ]
