# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20161123_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Timestamp',
            field=models.CharField(choices=[(b'CREATED', b'Order created'), (b'STK', b'Order sent to kitchen'), (b'STA', b'Order started'), (b'RDY', b'Order ready to be served'), (b'SER', b'Order served')], default=b'CREATED', max_length=6),
        ),
    ]
