# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Completed',
            field=models.BooleanField(default=0),
        ),
    ]
