# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20161123_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserProfile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 10, 0, 45, 607350, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
