# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_order_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Completed',
            field=models.BooleanField(default=1),
        ),
    ]
