# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20161126_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 27, 8, 33, 41, 964000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderedmenuitems',
            name='num_items',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
