# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20161123_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Timestamp',
            field=models.CharField(choices=[(b'CREATED', b'Order created'), (b'SENT TO KITCHEN', b'Order sent to kitchen'), (b'STARTED', b'Order started'), (b'READY', b'Order ready to be served'), (b'SERVED', b'Order served')], default=b'CREATED', max_length=15),
        ),
    ]
