# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
