# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20161116_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Name',
            new_name='Item_name',
        ),
    ]
