# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20161123_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[(b'CREATED', b'Order created'), (b'SENT TO KITCHEN', b'Order sent to kitchen'), (b'STARTED', b'Order started'), (b'READY', b'Order ready to be served'), (b'SERVED', b'Order served'), (b'COMPLETED', b'Order completed')], default=b'CREATED', max_length=15),
        ),
    ]
