# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 20:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20161113_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 13, 20, 53, 18, 307152, tzinfo=utc)),
        ),
    ]
