# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 05:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20161123_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 26, 5, 11, 39, 331605, tzinfo=utc)),
        ),
    ]
