# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20161116_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 16, 23, 17, 37, 540950, tzinfo=utc)),
        ),
    ]
