# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 03:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20161127_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 3, 33, 53, 229000, tzinfo=utc)),
        ),
    ]
