# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20161116_2317'),
        ('restaurant', '0008_auto_20161117_0002'),
    ]

    operations = [
    ]
