# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 03:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_merge_20161118_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 3, 42, 14, 509666, tzinfo=utc)),
        ),
    ]
