# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20161127_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 6, 6, 17, 846000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderedmenuitems',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
