# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20161127_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 28, 6, 6, 31, 581000, tzinfo=utc)),
        ),
    ]
