# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0014_auto_20161128_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenuitems',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 4, 8, 15, 31000, tzinfo=utc)),
        ),
    ]
