# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20161128_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenuitems',
            name='notes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderedmenuitems',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='StartTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 29, 7, 31, 24, 629000, tzinfo=utc)),
        ),
    ]
