# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_orderedmenuitems'),
        ('restaurant', '0016_auto_20161128_2331'),
    ]

    operations = [
    ]
