# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20161203_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenuitems',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderedmenuitems',
            name='status',
            field=models.CharField(choices=[(b'CREATED', b'Order created'), (b'SENT TO KITCHEN', b'Order sent to kitchen'), (b'STARTED', b'Order started'), (b'READY', b'Order ready to be served'), (b'SERVED', b'Order served'), (b'COMPLETED', b'Order completed')], default=b'CREATED', max_length=15),
        ),
    ]
