# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20161203_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmenuitems',
            name='start_time',
        ),
    ]
