# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_orderedmenuitems_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmenuitems',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderedmenuitems',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='OrderedMenuItems',
        ),
    ]
