# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0022_auto_20161203_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedMenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_items', models.IntegerField(default=0)),
                ('notes', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(choices=[(b'CREATED', b'Order created'), (b'SENT TO KITCHEN', b'Order sent to kitchen'), (b'STARTED', b'Order started'), (b'READY', b'Order ready to be served'), (b'SERVED', b'Order served'), (b'COMPLETED', b'Order completed')], default=b'CREATED', max_length=15)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order')),
            ],
        ),
    ]
